/**
 * @license
 * Copyright 2025 Qwen Team
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Hardcoded schemas for the @qwen-code/open-computer-use tools.
 *
 * Pinned to: @qwen-code/open-computer-use@0.2.3
 * (Exact pin — see PINNED_OPEN_COMPUTER_USE_PACKAGE_NAME /
 * PINNED_OPEN_COMPUTER_USE_VERSION in constants.ts for the canonical
 * package + version and bump procedure.)
 *
 * Verified against the published package: `tools/list` returns the
 * same 9 tools (click, drag, get_app_state, list_apps,
 * perform_secondary_action, press_key, scroll, set_value, type_text).
 * The 0.2.0 → 0.2.3 changes (notarization, the window-free
 * `permission-status` CLI command, the screenshot minScale-clamp fix) do
 * not alter the MCP tool surface, so these schemas are unchanged across
 * all of them.
 *
 * Regenerated by scripts/sync-computer-use-schemas.ts — do not hand-edit.
 */

export interface ComputerUseToolSchema {
  description: string;
  parameterSchema: Record<string, unknown>;
}

export const COMPUTER_USE_TOOL_NAMES = [
  'click',
  'drag',
  'get_app_state',
  'list_apps',
  'perform_secondary_action',
  'press_key',
  'scroll',
  'set_value',
  'type_text',
] as const;

export type ComputerUseToolName = (typeof COMPUTER_USE_TOOL_NAMES)[number];

export const COMPUTER_USE_SCHEMAS: Record<
  ComputerUseToolName,
  ComputerUseToolSchema
> = {
  click: {
    description:
      'Click an element by index or pixel coordinates from screenshot. This tool is part of plugin `Computer Use`.',
    parameterSchema: {
      type: 'object',
      properties: {
        click_count: {
          type: 'integer',
          description: 'Number of clicks. Defaults to 1',
        },
        mouse_button: {
          description: 'Mouse button to click. Defaults to left.',
          enum: ['left', 'right', 'middle'],
          type: 'string',
        },
        element_index: {
          type: 'string',
          description: 'Element index to click',
        },
        y: {
          type: 'number',
          description: 'Y coordinate in screenshot pixel coordinates',
        },
        app: {
          type: 'string',
          description: 'App name or bundle identifier',
        },
        x: {
          description: 'X coordinate in screenshot pixel coordinates',
          type: 'number',
        },
      },
      required: ['app'],
      additionalProperties: false,
    },
  },
  drag: {
    description:
      'Drag from one point to another using pixel coordinates. This tool is part of plugin `Computer Use`.',
    parameterSchema: {
      type: 'object',
      properties: {
        app: {
          type: 'string',
          description: 'App name or bundle identifier',
        },
        from_x: {
          description: 'Start X coordinate',
          type: 'number',
        },
        from_y: {
          type: 'number',
          description: 'Start Y coordinate',
        },
        to_x: {
          description: 'End X coordinate',
          type: 'number',
        },
        to_y: {
          type: 'number',
          description: 'End Y coordinate',
        },
      },
      required: ['app', 'from_x', 'from_y', 'to_x', 'to_y'],
      additionalProperties: false,
    },
  },
  get_app_state: {
    description:
      "Start an app use session if needed, then get the state of the app's key window and return a screenshot and accessibility tree. This must be called once per assistant turn before interacting with the app. This tool is part of plugin `Computer Use`.",
    parameterSchema: {
      type: 'object',
      properties: {
        app: {
          description: 'App name or bundle identifier',
          type: 'string',
        },
      },
      required: ['app'],
      additionalProperties: false,
    },
  },
  list_apps: {
    description:
      'List the apps on this computer. Returns the set of apps that are currently running, as well as any that have been used in the last 14 days, including details on usage frequency. This tool is part of plugin `Computer Use`.',
    parameterSchema: {
      type: 'object',
      properties: {},
      additionalProperties: false,
    },
  },
  perform_secondary_action: {
    description:
      'Invoke a secondary accessibility action exposed by an element. This tool is part of plugin `Computer Use`.',
    parameterSchema: {
      type: 'object',
      properties: {
        action: {
          description: 'Secondary accessibility action name',
          type: 'string',
        },
        app: {
          description: 'App name or bundle identifier',
          type: 'string',
        },
        element_index: {
          description: 'Element identifier',
          type: 'string',
        },
      },
      required: ['app', 'element_index', 'action'],
      additionalProperties: false,
    },
  },
  press_key: {
    description:
      'Press a key or key-combination on the keyboard, including modifier and navigation keys.\n  - This supports xdotool\'s `key` syntax.\n  - Examples: "a", "Return", "Tab", "super+c", "Up", "KP_0" (for the numpad 0 key). This tool is part of plugin `Computer Use`.',
    parameterSchema: {
      type: 'object',
      properties: {
        app: {
          description: 'App name or bundle identifier',
          type: 'string',
        },
        key: {
          type: 'string',
          description: 'Key or key combination to press',
        },
      },
      required: ['app', 'key'],
      additionalProperties: false,
    },
  },
  scroll: {
    description:
      'Scroll an element in a direction by a number of pages. This tool is part of plugin `Computer Use`.',
    parameterSchema: {
      type: 'object',
      properties: {
        pages: {
          type: 'number',
          description:
            'Number of pages to scroll. Fractional values are supported. Defaults to 1',
        },
        app: {
          description: 'App name or bundle identifier',
          type: 'string',
        },
        element_index: {
          description: 'Element identifier',
          type: 'string',
        },
        direction: {
          description: 'Scroll direction: up, down, left, or right',
          type: 'string',
        },
      },
      required: ['app', 'element_index', 'direction'],
      additionalProperties: false,
    },
  },
  set_value: {
    description:
      'Set the value of a settable accessibility element. This tool is part of plugin `Computer Use`.',
    parameterSchema: {
      type: 'object',
      properties: {
        element_index: {
          type: 'string',
          description: 'Element identifier',
        },
        value: {
          type: 'string',
          description: 'Value to assign',
        },
        app: {
          description: 'App name or bundle identifier',
          type: 'string',
        },
      },
      required: ['app', 'element_index', 'value'],
      additionalProperties: false,
    },
  },
  type_text: {
    description:
      'Type literal text using keyboard input. This tool is part of plugin `Computer Use`.',
    parameterSchema: {
      type: 'object',
      properties: {
        app: {
          type: 'string',
          description: 'App name or bundle identifier',
        },
        text: {
          type: 'string',
          description: 'Literal text to type',
        },
      },
      required: ['app', 'text'],
      additionalProperties: false,
    },
  },
};
