/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated / vendored file detection for attribution exclusion.
 * Based on GitHub Linguist vendored patterns and common generated file patterns.
 */

import { basename, extname, posix, sep } from 'node:path';

// Exact file name matches (case-insensitive)
const EXCLUDED_FILENAMES = new Set([
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'bun.lockb',
  'bun.lock',
  'composer.lock',
  'gemfile.lock',
  'cargo.lock',
  'poetry.lock',
  'pipfile.lock',
  'shrinkwrap.json',
  'npm-shrinkwrap.json',
  // Terraform: provider lockfile generated by `terraform init`. In
  // Terraform repos this file often dominates a commit's churn and
  // would skew per-file AI ratios toward provider noise rather than
  // the human-authored Terraform sources the note is meant to
  // describe.
  '.terraform.lock.hcl',
]);

// File extension patterns (case-insensitive). Note: `.d.ts` is NOT
// listed here — `.d.ts` files are commonly authored by hand
// (declaration files for projects without TS sources, ambient module
// declarations, asset shims like `*.d.ts` for `import './x.svg'`),
// and treating every one as generated would silently drop AI edits
// to those files. Auto-generated `.d.ts` (e.g. `tsc --declaration`
// output) tends to live under `/dist/`, `/build/`, or `/out/`,
// which are already covered by `EXCLUDED_DIRECTORY_SEGMENTS`.
const EXCLUDED_EXTENSIONS = new Set([
  '.min.js',
  '.min.css',
  '.min.html',
  '.bundle.js',
  '.bundle.css',
  '.generated.ts',
  '.generated.js',
]);

// Directory segments that indicate generated/vendored content. Compared
// against path segments (split on `/`) rather than substrings, so a
// project dir named `my-dist` or `xbuild` doesn't get caught by a
// `/dist/` substring match and silently drop AI attribution.
const EXCLUDED_DIRECTORY_SEGMENTS = new Set([
  'dist',
  'build',
  'out',
  'output',
  'node_modules',
  'vendor',
  'vendored',
  'third_party',
  'third-party',
  'external',
  '.next',
  '.nuxt',
  '.svelte-kit',
  'coverage',
  '__pycache__',
  '.tox',
  'venv',
  '.venv',
]);

// Multi-segment directory patterns that need contiguous matches
// (e.g. `target/release` and `target/debug` for Rust — `target` alone
// is too noisy as it's a common app name too).
const EXCLUDED_DIRECTORY_PATH_SUFFIXES = ['target/release', 'target/debug'];

// Filename patterns using regex for more complex matching
const EXCLUDED_FILENAME_PATTERNS = [
  /^.*\.min\.[a-z]+$/i,
  /^.*-min\.[a-z]+$/i,
  /^.*\.bundle\.[a-z]+$/i,
  /^.*\.generated\.[a-z]+$/i,
  /^.*\.gen\.[a-z]+$/i,
  /^.*\.auto\.[a-z]+$/i,
  /^.*_generated\.[a-z]+$/i,
  /^.*_gen\.[a-z]+$/i,
  /^.*\.pb\.(go|js|ts|py|rb)$/i,
  /^.*_pb2?\.py$/i,
  /^.*\.pb\.h$/i,
  /^.*\.grpc\.[a-z]+$/i,
  /^.*\.swagger\.[a-z]+$/i,
  /^.*\.openapi\.[a-z]+$/i,
];

/**
 * Check if a file should be excluded from attribution based on Linguist-style rules.
 *
 * @param filePath - Relative file path from repository root
 * @returns true if the file should be excluded from attribution
 */
export function isGeneratedFile(filePath: string): boolean {
  const normalizedPath =
    posix.sep + filePath.split(sep).join(posix.sep).replace(/^\/+/, '');
  const fileName = basename(filePath).toLowerCase();
  const ext = extname(filePath).toLowerCase();

  if (EXCLUDED_FILENAMES.has(fileName)) {
    return true;
  }

  if (EXCLUDED_EXTENSIONS.has(ext)) {
    return true;
  }

  // Check for compound extensions like .min.js
  const parts = fileName.split('.');
  if (parts.length > 2) {
    const compoundExt = '.' + parts.slice(-2).join('.');
    if (EXCLUDED_EXTENSIONS.has(compoundExt)) {
      return true;
    }
  }

  const normalizedPathLower = normalizedPath.toLowerCase();
  // Segment-boundary check: split on `/` and test each segment against
  // EXCLUDED_DIRECTORY_SEGMENTS so `/repo/my-dist/file.ts` (a literal
  // dir name) doesn't get caught by the `dist` rule the way a naïve
  // `.includes('/dist/')` substring match could appear to suggest.
  const segments = normalizedPathLower.split('/').filter(Boolean);
  // The last segment is the filename — directory rules only apply to
  // intermediate path components.
  for (const seg of segments.slice(0, -1)) {
    if (EXCLUDED_DIRECTORY_SEGMENTS.has(seg)) {
      return true;
    }
  }
  for (const suffix of EXCLUDED_DIRECTORY_PATH_SUFFIXES) {
    if (normalizedPathLower.includes(`/${suffix}/`)) {
      return true;
    }
  }

  for (const pattern of EXCLUDED_FILENAME_PATTERNS) {
    if (pattern.test(fileName)) {
      return true;
    }
  }

  return false;
}
