/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import { describe, it, expect } from 'vitest';
import { isGeneratedFile } from './generatedFiles.js';

describe('isGeneratedFile', () => {
  it('should exclude lock files', () => {
    expect(isGeneratedFile('package-lock.json')).toBe(true);
    expect(isGeneratedFile('yarn.lock')).toBe(true);
    expect(isGeneratedFile('pnpm-lock.yaml')).toBe(true);
    expect(isGeneratedFile('Cargo.lock')).toBe(true);
  });

  it('should exclude minified files', () => {
    expect(isGeneratedFile('app.min.js')).toBe(true);
    expect(isGeneratedFile('styles.min.css')).toBe(true);
    expect(isGeneratedFile('lib-min.js')).toBe(true);
  });

  it('should exclude files in dist/build directories', () => {
    expect(isGeneratedFile('dist/bundle.js')).toBe(true);
    expect(isGeneratedFile('build/output.js')).toBe(true);
    expect(isGeneratedFile('src/.next/cache.js')).toBe(true);
  });

  // `.d.ts` files are commonly authored by hand (declaration files
  // for projects without TS sources, ambient module declarations,
  // asset shims like `*.d.ts` for `import './x.svg'`); the prior
  // blanket exclusion silently dropped AI edits to those files.
  // Auto-generated `.d.ts` (e.g. `tsc --declaration` output) tends
  // to live under `/dist/` etc. and is still excluded by the
  // directory rules.
  it('should NOT exclude hand-authored TypeScript declaration files', () => {
    expect(isGeneratedFile('types/index.d.ts')).toBe(false);
    expect(isGeneratedFile('src/assets.d.ts')).toBe(false);
  });

  it('should still exclude .d.ts emitted into build directories', () => {
    expect(isGeneratedFile('dist/index.d.ts')).toBe(true);
    expect(isGeneratedFile('build/types.d.ts')).toBe(true);
  });

  it('should exclude generated code files', () => {
    expect(isGeneratedFile('api.generated.ts')).toBe(true);
    expect(isGeneratedFile('schema.pb.go')).toBe(true);
    expect(isGeneratedFile('service.grpc.ts')).toBe(true);
  });

  it('should exclude vendor directories', () => {
    expect(isGeneratedFile('vendor/lib/utils.js')).toBe(true);
    expect(isGeneratedFile('node_modules/pkg/index.js')).toBe(true);
  });

  it('should NOT exclude normal source files', () => {
    expect(isGeneratedFile('src/main.ts')).toBe(false);
    expect(isGeneratedFile('lib/utils.js')).toBe(false);
    expect(isGeneratedFile('README.md')).toBe(false);
    expect(isGeneratedFile('package.json')).toBe(false);
    expect(isGeneratedFile('src/components/Button.tsx')).toBe(false);
  });

  // Segment-boundary check: project dirs that *contain* a reserved
  // word as a substring (e.g. `my-dist`, `xbuild`, `prebuild`) must
  // not be caught by the directory rule.
  it('should NOT exclude dirs that merely substring-match a reserved name', () => {
    expect(isGeneratedFile('my-dist/file.ts')).toBe(false);
    expect(isGeneratedFile('xbuild/core.ts')).toBe(false);
    expect(isGeneratedFile('rebuild/notes.md')).toBe(false);
    expect(isGeneratedFile('preout/x.ts')).toBe(false);
    // The filename itself isn't subject to the directory rule.
    expect(isGeneratedFile('src/dist.ts')).toBe(false);
  });

  // `.lock` is no longer a blanket exclusion — only the explicit
  // EXCLUDED_FILENAMES (yarn.lock etc.) are dropped.
  it('should NOT exclude unknown .lock files (only well-known ones)', () => {
    expect(isGeneratedFile('config/feature.lock')).toBe(false);
    // Sanity: known lockfiles still excluded.
    expect(isGeneratedFile('yarn.lock')).toBe(true);
  });

  // Terraform: `.terraform.lock.hcl` is generated by `terraform init`
  // and dominates Terraform-repo commits. Listed as a known
  // generated lockfile in EXCLUDED_FILENAMES.
  it('should exclude Terraform provider lockfile', () => {
    expect(isGeneratedFile('.terraform.lock.hcl')).toBe(true);
    expect(isGeneratedFile('infra/modules/network/.terraform.lock.hcl')).toBe(
      true,
    );
  });
});
