/**
 * @license
 * Copyright 2025 Qwen Team
 * SPDX-License-Identifier: Apache-2.0
 *
 * Settings writer for VSCode extension.
 * Handles bidirectional sync between VSCode Settings and ~/.qwen/settings.json.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  ALL_PROVIDERS,
  AuthType,
  CUSTOM_API_KEY_ENV_PREFIX,
  Storage,
  applyProviderInstallPlan,
  resolveMetadataKey,
  type ProviderInstallPlan,
  type ProviderSettingsAdapter,
  type ModelProvidersConfig,
} from '@qwen-code/qwen-code-core';
import {
  CODING_PLAN_ENV_KEY,
  CodingPlanRegion,
  SUBSCRIPTION_PLAN_OPTIONS,
  findSubscriptionPlanByConfig,
  getSubscriptionPlanConfig,
  isSubscriptionPlanConfig,
} from './subscriptionPlanDefinitions.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Mode for ~/.qwen/settings.json — owner-only read/write. The unified install
 * plan now persists API keys into `env.*` inside this file, so on multi-user
 * systems the default 0644 (process umask) would expose those secrets to any
 * local user. Keep this in sync with `loadedSettingsAdapter`'s expectations.
 */
const SETTINGS_FILE_MODE = 0o600;
/** Directory mode for ~/.qwen — owner-only. */
const SETTINGS_DIR_MODE = 0o700;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Model providers as key-value map: modelId → baseUrl.
 * This is the format VSCode Settings UI can render as an editable table.
 */
export type VSCodeModelProviders = Record<string, string>;

/**
 * Values extracted from ~/.qwen/settings.json for populating VSCode Settings.
 */
export interface QwenSettingsForVSCode {
  provider: 'coding-plan' | 'api-key';
  apiKey: string;
  codingPlanRegion: 'china' | 'global';
}

// ---------------------------------------------------------------------------
// Low-level read/write helpers
// ---------------------------------------------------------------------------

/**
 * Length of a JSON escape sequence starting with `\\`. Handles the six-char
 * `\\uXXXX` form — otherwise a value like `"sk-abc\\u0022,..."` would let the
 * embedded `\\u0022` close the string early and the rest of the buffer would
 * parse as additional keys, enabling settings.json key injection.
 */
function jsonEscapeLength(text: string, backslashIdx: number): number {
  return text[backslashIdx + 1] === 'u' ? 6 : 2;
}

/**
 * Strip single-line (`//`) and multi-line comments from JSONC content
 * so that `JSON.parse` can handle ~/.qwen/settings.json files that
 * contain comments (common when hand-edited or generated by CLI).
 */
function stripJsonComments(text: string): string {
  let result = '';
  let i = 0;
  while (i < text.length) {
    // String literal — copy verbatim (handles escaped quotes)
    if (text[i] === '"') {
      let j = i + 1;
      while (j < text.length) {
        if (text[j] === '\\') {
          j += jsonEscapeLength(text, j);
        } else if (text[j] === '"') {
          j++;
          break;
        } else {
          j++;
        }
      }
      result += text.slice(i, j);
      i = j;
    } else if (text[i] === '/' && text[i + 1] === '/') {
      // Single-line comment — skip until newline
      const nl = text.indexOf('\n', i);
      i = nl === -1 ? text.length : nl;
    } else if (text[i] === '/' && text[i + 1] === '*') {
      // Multi-line comment — skip until */
      const end = text.indexOf('*/', i + 2);
      i = end === -1 ? text.length : end + 2;
    } else {
      result += text[i];
      i++;
    }
  }
  return result;
}

/**
 * Strip trailing commas inside arrays/objects (`,]` / `,}`) — VSCode's own
 * settings.json allows them and they crash strict JSON.parse. Uses a
 * character-by-character scanner so that the `,]` substring inside a string
 * literal (e.g. `"MY_VAR": ",]"`) is preserved unchanged — a regex would
 * silently rewrite it and corrupt the value.
 */
function stripTrailingCommas(text: string): string {
  let result = '';
  let i = 0;
  while (i < text.length) {
    const ch = text[i];
    if (ch === '"') {
      // Copy the entire string literal (including escapes) verbatim. Must
      // use the same jsonEscapeLength helper as stripJsonComments so that
      // `"` is not mis-parsed as `\u` + early-terminating `"`.
      let j = i + 1;
      while (j < text.length) {
        if (text[j] === '\\') {
          j += jsonEscapeLength(text, j);
          continue;
        }
        if (text[j] === '"') {
          j++;
          break;
        }
        j++;
      }
      result += text.slice(i, j);
      i = j;
      continue;
    }
    if (ch === ',') {
      // Drop comma only if the next non-whitespace char is } or ].
      let j = i + 1;
      while (j < text.length && /\s/.test(text[j]!)) j++;
      if (j < text.length && (text[j] === ']' || text[j] === '}')) {
        i++;
        continue;
      }
    }
    result += ch;
    i++;
  }
  return result;
}

/**
 * Read ~/.qwen/settings.json. Returns {} if the file is missing.
 * Parse errors are logged and re-thrown so callers don't silently destroy a
 * malformed file by treating it as empty and then overwriting it.
 * Handles JSONC (JSON with comments + trailing commas) for hand-edited files.
 */
function readSettings(): Record<string, unknown> {
  const settingsPath = Storage.getGlobalSettingsPath();
  let content: string;
  try {
    content = fs.readFileSync(settingsPath, 'utf-8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      return {};
    }
    throw err;
  }
  try {
    return JSON.parse(
      stripTrailingCommas(stripJsonComments(content)),
    ) as Record<string, unknown>;
  } catch (err) {
    // Surface an actionable message rather than the raw SyntaxError. The
    // caller's catch will see this; refusing to overwrite a malformed file
    // is the whole point — better than silently destroying user state by
    // treating it as `{}`.
    console.error(
      `[settingsWriter] Failed to parse ${settingsPath}; refusing to overwrite a malformed file.`,
      err,
    );
    const message =
      err instanceof Error ? `${err.name}: ${err.message}` : String(err);
    throw new Error(
      `Cannot parse ~/.qwen/settings.json (${message}). ` +
        `Standard JSONC (// comments, /* */, trailing commas) is supported, ` +
        `but non-standard JSON features (unquoted keys, single quotes) are not. ` +
        `Please fix or delete ${settingsPath} and try again.`,
      { cause: err instanceof Error ? err : undefined },
    );
  }
}

/**
 * Write ~/.qwen/settings.json atomically (temp file + rename), creating the
 * directory if needed. Atomic rename prevents leaving a half-written file
 * behind on EACCES / disk-full / process crash mid-write.
 */
function writeSettings(settings: Record<string, unknown>): void {
  const settingsPath = Storage.getGlobalSettingsPath();
  const dir = path.dirname(settingsPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true, mode: SETTINGS_DIR_MODE });
  }
  const tmpPath = `${settingsPath}.${process.pid}.${Date.now()}.tmp`;
  // Create the temp file with owner-only permissions so secrets in `env.*`
  // are never observable to other local users even briefly.
  fs.writeFileSync(tmpPath, JSON.stringify(settings, null, 2), {
    encoding: 'utf-8',
    mode: SETTINGS_FILE_MODE,
  });
  try {
    fs.renameSync(tmpPath, settingsPath);
  } catch (renameErr) {
    // renameSync can fail on Windows when a watcher / antivirus holds the
    // target (EPERM/EBUSY). The temp file otherwise lingers in ~/.qwen
    // containing API keys — clean it up so secrets don't accumulate on
    // disk across repeated failed writes.
    try {
      fs.unlinkSync(tmpPath);
    } catch {
      /* best-effort cleanup; surface the original rename error below */
    }
    throw renameErr;
  }
  // Tighten any pre-existing settings file inherited from older writes that
  // used the default umask. chmodSync is a no-op on the just-written file but
  // covers the case where the file was created earlier with looser bits.
  try {
    fs.chmodSync(settingsPath, SETTINGS_FILE_MODE);
  } catch {
    // Best effort — surface nothing to the user if the FS rejects chmod
    // (e.g. Windows, mounted FS without POSIX permissions).
  }
}

/**
 * Ensure nested objects exist at the given key path.
 */
function ensureNestedObject(
  obj: Record<string, unknown>,
  ...keys: string[]
): Record<string, unknown> {
  let current = obj;
  for (const key of keys) {
    if (!current[key] || typeof current[key] !== 'object') {
      current[key] = {};
    }
    current = current[key] as Record<string, unknown>;
  }
  return current;
}

/**
 * Find OpenAI-compatible model entries from modelProviders.
 * CLI uses AuthType.USE_OPENAI ('openai') as the key, but some legacy
 * configs may use other keys. Check both.
 */
function findOpenaiModels(
  modelProviders: Record<string, unknown> | undefined,
): Array<Record<string, unknown>> {
  if (!modelProviders) {
    return [];
  }
  for (const key of [AuthType.USE_OPENAI, 'use_openai']) {
    const arr = modelProviders[key];
    if (Array.isArray(arr) && arr.length > 0) {
      return arr as Array<Record<string, unknown>>;
    }
  }
  return [];
}

// ---------------------------------------------------------------------------
// Write: VSCode Settings → ~/.qwen/settings.json
// ---------------------------------------------------------------------------

/**
 * Write Coding Plan configuration to ~/.qwen/settings.json.
 * Auto-injects model providers from the regional template,
 * preserving any existing non-Coding-Plan entries.
 *
 * @returns The injected models as a VSCode key-value map (modelId → baseUrl)
 */
export function writeCodingPlanConfig(
  region: 'china' | 'global',
  apiKey: string,
): VSCodeModelProviders {
  const settings = readSettings();
  const codingRegion =
    region === 'global' ? CodingPlanRegion.GLOBAL : CodingPlanRegion.CHINA;
  const planConfig = getSubscriptionPlanConfig('coding', codingRegion);

  // Auth
  const auth = ensureNestedObject(settings, 'security', 'auth');
  auth.selectedType = AuthType.USE_OPENAI;

  // API key
  const env = ensureNestedObject(settings, 'env');
  env[CODING_PLAN_ENV_KEY] = apiKey;

  // Model providers — merge Coding Plan templates with existing non-CP entries
  const providers = ensureNestedObject(settings, 'modelProviders');
  const existing = findOpenaiModels(
    settings.modelProviders as Record<string, unknown>,
  );
  const nonCodingPlan = existing.filter(
    (e) => !isSubscriptionPlanConfig(e.baseUrl as string, e.envKey as string),
  );
  const planModels = planConfig.template.map((model) => ({
    ...model,
    envKey: planConfig.envKey,
  }));
  providers[AuthType.USE_OPENAI] = [...planModels, ...nonCodingPlan];

  // Coding Plan metadata — write to the providerMetadata namespace that
  // the CLI now reads from. Remove legacy top-level key if present.
  const providerMetadata = ensureNestedObject(settings, 'providerMetadata');
  providerMetadata['coding-plan'] = {
    region: codingRegion,
    version: planConfig.version,
  };
  delete settings.codingPlan;

  // Default model
  const defaultModelId = planConfig.template[0]?.id ?? 'qwen3.5-plus';
  settings.model = { name: defaultModelId };

  writeSettings(settings);

  // Return key-value map for VSCode settings
  const result: VSCodeModelProviders = {};
  for (const m of planConfig.template) {
    result[m.id] = m.baseUrl || '';
  }
  return result;
}

/**
 * Write model providers from VSCode Settings (key-value map) to ~/.qwen/settings.json.
 * Used when provider = "api-key" and user edits the modelProviders map.
 *
 * @param params.apiKey - The API key
 * @param params.modelProviders - Map of modelId → baseUrl
 * @param params.activeModel - Currently selected model ID
 */
export function writeModelProvidersConfig(params: {
  apiKey: string;
  modelProviders: VSCodeModelProviders;
  activeModel: string;
}): void {
  const settings = readSettings();

  // Auth
  const auth = ensureNestedObject(settings, 'security', 'auth');
  auth.selectedType = AuthType.USE_OPENAI;

  // API key
  const env = ensureNestedObject(settings, 'env');
  env['OPENAI_API_KEY'] = params.apiKey;
  for (const plan of SUBSCRIPTION_PLAN_OPTIONS) {
    delete env[plan.envKey];
  }

  // Convert key-value map to CLI's array format and merge with existing
  // non-target entries so reconfiguring one provider doesn't silently
  // delete others (e.g. Coding Plan entries with a different envKey).
  const providers = ensureNestedObject(settings, 'modelProviders');
  const modelArray = Object.entries(params.modelProviders).map(
    ([id, baseUrl]) => ({
      id,
      name: id,
      baseUrl: baseUrl || 'https://api.openai.com/v1',
      envKey: 'OPENAI_API_KEY',
    }),
  );
  const existing = findOpenaiModels(
    settings.modelProviders as Record<string, unknown>,
  );
  const nonTarget = existing.filter((e) => e.envKey !== 'OPENAI_API_KEY');
  providers[AuthType.USE_OPENAI] = [...modelArray, ...nonTarget];

  // Active model
  if (params.activeModel) {
    settings.model = { name: params.activeModel };
  }

  for (const plan of SUBSCRIPTION_PLAN_OPTIONS) {
    delete settings[plan.metadataKey];
  }
  const pm = settings.providerMetadata as Record<string, unknown> | undefined;
  if (pm) {
    delete pm['coding-plan'];
    delete pm['token-plan'];
  }

  writeSettings(settings);
}

// ---------------------------------------------------------------------------
// Unified install plan — bridges core's ProviderInstallPlan to file I/O
// ---------------------------------------------------------------------------

/**
 * Create a ProviderSettingsAdapter backed by ~/.qwen/settings.json.
 * Reads/writes use the low-level helpers already in this module.
 */
function createFileSettingsAdapter(): ProviderSettingsAdapter {
  let data = readSettings();
  let backupData: Record<string, unknown> | null = null;

  return {
    getValue(key: string): unknown {
      const parts = key.split('.');
      let current: unknown = data;
      for (const part of parts) {
        if (current == null || typeof current !== 'object') return undefined;
        current = (current as Record<string, unknown>)[part];
      }
      return current;
    },

    setValue(key: string, value: unknown): void {
      const parts = key.split('.');
      let current = data;
      for (let i = 0; i < parts.length; i++) {
        const part = parts[i]!;
        // Refuse to walk through prototype-pollution keys. ProviderInstallPlan
        // contents come from in-process callers, but install plans accept
        // arbitrary string keys (env vars, providerState namespaces) so the
        // input is untrusted enough to warrant the guard. Literal === checks
        // (not Set.has) are what CodeQL's prototype-pollution sanitiser
        // recognises — keep them at the only step that actually writes to
        // `current`.
        if (
          part === '__proto__' ||
          part === 'constructor' ||
          part === 'prototype'
        ) {
          throw new Error(
            `Refusing to write settings key with reserved segment: ${key}`,
          );
        }
        if (i === parts.length - 1) {
          current[part] = value;
          break;
        }
        const existing = Object.prototype.hasOwnProperty.call(current, part)
          ? current[part]
          : undefined;
        if (existing == null) {
          current[part] = {};
        } else if (Array.isArray(existing) || typeof existing !== 'object') {
          // Refuse to silently overwrite a scalar (or treat an array as an
          // object) at an intermediate segment — would either destroy user
          // data (e.g. {"env": "legacy-string"} losing the string when
          // env.NEW_KEY is written) or set string keys on an array.
          throw new Error(
            `Cannot write settings key "${key}": segment "${part}" is ${
              Array.isArray(existing) ? 'an array' : `a ${typeof existing}`
            }, not an object`,
          );
        }
        current = current[part] as Record<string, unknown>;
      }
    },

    getModelProviders(): ModelProvidersConfig {
      return (data.modelProviders ?? {}) as ModelProvidersConfig;
    },

    persist(): void {
      writeSettings(data);
    },

    backup(): void {
      backupData = JSON.parse(JSON.stringify(data)) as Record<string, unknown>;
    },

    restore(): void {
      if (!backupData) return;
      // Write to disk FIRST. If writeSettings throws (EACCES / disk full /
      // EPERM on Windows), the in-memory update is skipped on purpose:
      // callers never observe a clean snapshot while the file on disk lies.
      //
      // Note: the CLI adapter (loadedSettingsAdapter) takes a different
      // trade-off — restoreSettingsFromBackup() returns a boolean, so it
      // logs on failure and *unconditionally* restores in-memory state.
      // VS Code can be stricter because its writeSettings is the only path
      // and a throw here is recoverable; the CLI lacks that escape hatch.
      writeSettings(backupData);
      data = backupData;
      backupData = null;
    },

    cleanupBackup(): void {
      backupData = null;
    },
  };
}

/**
 * Apply a ProviderInstallPlan to ~/.qwen/settings.json.
 * This is the primary entry point for the VSCode interactive auth flow.
 *
 * `applyProviderInstallPlan` is async, so a returned (or thrown) Promise must
 * be awaited — otherwise an `EACCES` from `persist()` or the prototype-pollution
 * guard in `setValue()` would be swallowed and the caller would carry on
 * reconnecting the agent as if the settings write had succeeded.
 */
export async function applyProviderInstallPlanToFile(
  plan: ProviderInstallPlan,
): Promise<void> {
  const settings = createFileSettingsAdapter();
  await applyProviderInstallPlan(plan, { settings });
}

/**
 * Capture a deep-cloned snapshot of the current on-disk settings for rollback,
 * or `null` if the file is missing/unreadable.
 *
 * Unlike `readSettings`, this never throws — callers use it to checkpoint
 * before `applyProviderInstallPlanToFile` so that a *later* step the install
 * plan can't see (e.g. the agent reconnect rejecting a bad API key) can be
 * undone via {@link restoreSettingsSnapshot}. `applyProviderInstallPlan`'s own
 * backup/restore only covers failures *inside* the plan; the
 * disconnect/reconnect in WebViewProvider runs after `cleanupBackup`, so the
 * caller owns that rollback window.
 */
export function snapshotSettingsForRollback(): Record<string, unknown> | null {
  try {
    return structuredClone(readSettings());
  } catch (err) {
    // Leave a breadcrumb: returning null disables credential rollback, so if
    // settings are transiently unreadable (AV lock, disk hiccup) the oncall
    // engineer can tie repeated cross-restart auth failures back to here.
    // Log only the error's class name (not its message) — consistent with the
    // providerMatchesCredentials guard, so the security stance holds even
    // though this catch is filesystem errors rather than user-defined fns.
    console.warn(
      '[settingsWriter] snapshotSettingsForRollback failed; credential rollback disabled:',
      err instanceof Error ? err.constructor.name : typeof err,
    );
    return null;
  }
}

/**
 * Write a snapshot captured by {@link snapshotSettingsForRollback} back to
 * disk. No-op when the snapshot is `null` (nothing safe to restore).
 */
export function restoreSettingsSnapshot(
  snapshot: Record<string, unknown> | null,
): void {
  if (snapshot === null) return;
  writeSettings(snapshot);
}

// ---------------------------------------------------------------------------
// Read: ~/.qwen/settings.json → VSCode Settings
// ---------------------------------------------------------------------------

/**
 * Read ~/.qwen/settings.json and extract values for VSCode Settings UI.
 * Returns null if no valid configuration found, or if the file is
 * malformed — the panel falls back to the empty/default state instead of
 * crashing the extension on activation. `readSettings` itself now throws
 * on parse failure (so we never silently overwrite a corrupt file in the
 * write paths), so this caller has to catch.
 */
export function readQwenSettingsForVSCode(): QwenSettingsForVSCode | null {
  let settings: Record<string, unknown>;
  try {
    settings = readSettings();
  } catch (error) {
    console.error(
      '[settingsWriter] readQwenSettingsForVSCode failed; returning null:',
      error,
    );
    return null;
  }

  const security = settings.security as Record<string, unknown> | undefined;
  const auth = security?.auth as Record<string, unknown> | undefined;
  if (!auth?.selectedType) {
    return null;
  }

  const env = (settings.env ?? {}) as Record<string, string>;
  const modelProviders = settings.modelProviders as
    | Record<string, unknown>
    | undefined;
  const openaiModels = findOpenaiModels(modelProviders);
  const subscriptionPlan = openaiModels
    .map((model) =>
      findSubscriptionPlanByConfig(
        model.baseUrl as string | undefined,
        model.envKey as string | undefined,
      ),
    )
    .find((match) => match !== undefined && !!env[match.plan.envKey]);

  if (subscriptionPlan?.plan.id === 'coding') {
    const region = subscriptionPlan.region === 'global' ? 'global' : 'china';
    return {
      provider: 'coding-plan',
      apiKey: env[subscriptionPlan.plan.envKey] || '',
      codingPlanRegion: region,
    };
  }

  // Non-Coding-Plan — find API key from model providers
  const firstEnvKey = (openaiModels[0]?.envKey as string) || 'OPENAI_API_KEY';
  const apiKey = env[firstEnvKey] || '';

  if (!apiKey) {
    return null;
  }

  return {
    provider: 'api-key',
    apiKey,
    codingPlanRegion: 'china',
  };
}

/**
 * Clear persisted auth credentials from ~/.qwen/settings.json.
 * Removes API keys, auth type selection, and coding plan metadata
 * so runtime state matches the cleared VS Code settings.
 */
export function clearPersistedAuth(): void {
  try {
    const settings = readSettings();

    // Remove auth type selection
    const security = settings.security as Record<string, unknown> | undefined;
    if (security?.auth) {
      delete (security.auth as Record<string, unknown>).selectedType;
    }

    // Remove API keys: every preset's string envKey + any custom-provider
    // env var (prefix-matched). Without this, third-party (DeepSeek /
    // MiniMax / Z.AI / IdeaLab / ModelScope / OpenRouter) and custom
    // (QWEN_CUSTOM_API_KEY_*) keys would linger on disk after the user
    // clears authentication.
    const env = settings.env as Record<string, unknown> | undefined;
    if (env) {
      // Subscription plan keys (kept explicit in case the provider list
      // ever drifts from SUBSCRIPTION_PLAN_OPTIONS).
      for (const plan of SUBSCRIPTION_PLAN_OPTIONS) {
        delete env[plan.envKey];
      }
      // Standard OpenAI bucket (legacy + the api-key flow's default).
      delete env['OPENAI_API_KEY'];
      // Every preset provider with a static string envKey.
      for (const p of ALL_PROVIDERS) {
        if (typeof p.envKey === 'string') {
          delete env[p.envKey];
        }
      }
      // Custom-provider env keys are derived dynamically by
      // generateCustomEnvKey — match the prefix instead of enumerating.
      for (const key of Object.keys(env)) {
        if (key.startsWith(CUSTOM_API_KEY_ENV_PREFIX)) {
          delete env[key];
        }
      }
    }

    // Remove subscription plan metadata (legacy + new namespace)
    for (const plan of SUBSCRIPTION_PLAN_OPTIONS) {
      delete settings[plan.metadataKey];
    }
    const pm = settings.providerMetadata as Record<string, unknown> | undefined;
    if (pm) {
      // Every preset with a static models[] writes providerMetadata.<id>.version
      // via resolveProviderState — wipe them all on clear so stale entries
      // don't cause phantom "update available" notifications for a provider
      // the user just signed out of. resolveMetadataKey throws when a future
      // provider has '.' in its id; wrap per-iteration so one bad entry
      // can't abort the whole cleanup and leave secrets on disk.
      for (const p of ALL_PROVIDERS) {
        try {
          const key = resolveMetadataKey(p);
          if (key) delete pm[key];
        } catch {
          /* skip metadata cleanup for a misconfigured provider id */
        }
      }
    }

    writeSettings(settings);
  } catch (error) {
    console.error(
      '[settingsWriter] Failed to clear persisted auth credentials:',
      error,
    );
  }
}
